apiVersion: v1
kind: Pod
metadata:
  name: nginxemptyDir
  labels:
    project: roboshop
    component: dev
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
       - name: nginx-logs
         mountPath: /var/logs/nginx
  volumes:
    - name: nginx-logs
      emptyDir:
        sizeLimit: 100Mi
