apiVersion: v1
kind: pod
metadata:
  name: nginx-emptyDir
  Labels:
    project: roboshop
    component: dev
specifications:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
       - name: nginx-logs
         mountPath: /var/logs/nginx
  volumes:
    - name: nginx-logs
      emptyDir:
        sizeLimit: 100Mi
