apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-0e1bee937536f01b1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static-pvc
spec:
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: ebs-static-pv  # Explicitly binds to your static PV
  storageClassName: "" 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebsnginx
spec:
  replicas: 2
  selector:
    matchLabels:
      project: roboshop
  template:
    metadata:
      labels:
        project: roboshop
    spec:
      containers:
        - name: nginx
          image: nginx
          volumes:
          - name: ebsstatic
            mountPath:  /var/lib/nginx
      volumes:
      - name: ebsstatic
        persistentVolumeClaim:
         claimName: efs-static-pvc

      