apiVersion: v1
kind: Pod
metadata:
  name: annotpod
  labels:
    project: roboshop
    environment: dev
  annotations:
    imageregistry: "https://hub.docker.com/"
    jenkins-build-url: "https://jenkins.joindevops.com/build/roboshop/job/2"
spec:
  containers:
    - name: redis
      image: redis  
    - name: bash
      image: bash