apiVersion: v1
kind: Pod
metadata:
  name: podenv
  namespace: roboshop
  labels: 
    project: roboshop
    environment: dev
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: component
          value: "app"
    - name: redis
      image: redis
      env:
       - name: component
         value: "db"