apiVersion: v1
kind: ConfigMap
metadata:
  name: poddata
data:
  project: roboshop
  envoionment: dev
  password: DevOps321

------------------

apiVersion: v1
kind: Pod
metadata: 
  name: podconigmap
spec:
  containers:
    - name: nginx
      image: nginx 
      envFrom:
        - configMapRef:
            name: ConfigMap
  