apiVersion: v1
kind: Secret
metadata:
  name: podsecret
data:
  username: ec2-user
  password: DevOps321

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
    - name: nginx-pod
      image: nginx
      envFrom:
        - SecretRef: 
            name: podsecret