apiVersion: v1
kind: Secret
metadata:
  name: podsecret
data:
  username: ZWMyLXVzZXIK
  password: RGV2T3BzMzIxCg==

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
    - name: nginx-pod
      image: nginx
      envFrom:
        - secretRef: 
            name: podsecret