apiVersion: v1
kind: Service
metadata:
  name: nodeportfornginx
spec:
   type: NodePort
   selector:
     #project: roboshop
     #tier: frontend
     app.kubernetes.io/component: frontend
   ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30007