apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    project: roboshop
    tier: frontend
spec:
  replicas: 3
  selector:
    app.kubernetes.io/component: frontend
   #matchLabels:
     #project: roboshop
     #tier: frontend
  #POD Defination  
  template:
    metadata:
     labels:
       project: roboshop
       tier: frontend
       app.kubernetes.io/component: frontend
    spec:
      containers:
       - name: nginx-container
         image: nginx
  #ports:
  #    - protocol: TCP
   #     port: 8089
   #     targetPort: 80
   #     nodePort: 30008
       
