apiVersion: apps/v1
kind: Replicaset
metadata:
  name: nginx-re
  labels:
    project: roboshop
    tier: frontend
  spec:
    replicas: 3
    selector:
     matchLabels:
       project: roboshop
       tier: frontend
       app.kubernetes.io/component: frontend
  #POD Defination  
    template:
      name: nginx
      image: nginx
      labels:
        project: roboshop
        tier: frontend
        app.kubernetes.io/component: frontend
      ports:
        - protocol: TCP
          targetPort: 8080
          Port: 80
          NodePort: 30008
       
