apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replica
  labels:
    project: roboshop
    environment: dev
    purpose: demo
spec:
  ### No of replicas
  replicas: 5
  selector:
    matchLabels:
      project: roboshop
      tier: frontend
      app.kubernetes.io/component: frontend
  #pod defination
  template:
    metadata:
      labels:
        project: roboshop
        tier: frontend
        app.kubernetes.io/component: frontend
      spec:
        containers:
      - name: nginx-rs
        image: nginx