apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    component: frontend
spec:
    replicas: 3
    selector:
     matchLabels:
         project: roboshop
         tier: frontend
         app.kubernetes.io/component: frontend
    template:
      metadata:
        labels:
          project: roboshop
          tier: frontend
          app.kubernetes.io/component: frontend
      spec:
        containers:
            - name: nginx
              image: nginx  